{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-graphql-gateway.fullname" . }}
  labels:
    {{- include "kubernetes-graphql-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-graphql-gateway.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-graphql-gateway.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
